name: CI

on:
  push:
    branches: [main]
    tags: ['v*']  # IMPORTANT: Also trigger on tags for release process
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install peer dependencies
      run: npm install @orcdkestrator/core@latest --no-save
    
    - name: Run linter
      run: npm run lint
    
    - name: Run tests
      run: npm run test:coverage
    
    - name: Build
      run: npm run build
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}